keys:
  - &master_age age1y9gaaecnrvcqx2wdgv4y4ca4nclz3447mvfze97u0krhzlm2zpzsrnreng
  - &cricro_pc age179xlc7hrhzlzjatrfjr5a5puldkxqzar7k36409w2dxhh9rxr42q2745tl
  - &cricro_laptop age1xk55pvdly05kxl5sxgt4vmczalyw4vmzyrehg5ttqcjz8acvvg5s6nyval
  - &cricro_vm age1kkmrsy3ctfcdxeqh3rm3u2w8sh6aaj0f5n5t376k8prsuq5das3q6era99
  - &cricro_l2 age1gzlg6wj6aqened2p545fvacznlnmmp0naq920wdpxn3ks8kmyfrq9hxvh4
creation_rules:
  - path_regex: provisioning/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *master_age
          - *cricro_pc
          - *cricro_laptop
  - path_regex: secrets/.*
    key_groups:
      - age:
          - *master_age
          - *cricro_pc
          - *cricro_laptop
          - *cricro_vm
          - *cricro_l2
