-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "1920x1080@60.008", position = "0x1080", scale = 1, vrr = 0 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "1920x0", scale = 1, vrr = 0 })
