# Generated by nixos-anywhere at install time via
#   --generate-hardware-config nixos-facter ./modules/nixos/hosts/_hardware/bootstrap.json
{ ... }:
{
  flake.modules.nixos."hosts/_hardware/bootstrap" =
    { ... }:
    {
      # hardware.facter.reportPath = ./bootstrap.json;
    };
}
