hostname cricro-l2
    color_scheme ./ssh-themes/cricro-l2.conf

hostname cricro-laptop
    color_scheme ./ssh-themes/cricro-laptop.conf

hostname cricro-pc
    color_scheme ./ssh-themes/cricro-pc.conf

hostname cricro-vm
    color_scheme ./ssh-themes/cricro-vm.conf
