-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

local mocha = require("mocha")
local mauve = "0xff" .. mocha.mauveAlpha
local flamingo = "0xff" .. mocha.flamingoAlpha
local subtext0 = "0xff" .. mocha.subtext0Alpha

hl.config({ autogenerated = false })

hl.on("hyprland.start", function()
  hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user start hyprland-session.target")
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("cliphist")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("mutagen daemon start")
end)

-- Global Variables / Environment
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("QT_QPA_PLATFORMTHEME_QT6", "gtk3")

hl.config({
  input = {
    kb_layout = "latam,br",
    kb_variant = "",
    numlock_by_default = true,
    follow_mouse = 1,
    touchpad = {
      tap_to_click = true,
      natural_scroll = true,
    },
  },
  general = {
    gaps_in = 2,
    gaps_out = 6,
    border_size = 3,
    col = {
      active_border = {
        colors = { mauve, flamingo },
        angle = 90
      },
      inactive_border = subtext0,
    },
    resize_on_border = true,
    layout = "dwindle",
  },
  decoration = {
    rounding = 4,
    active_opacity = 1.0,
    inactive_opacity = 1.0,
    blur = {
      enabled = false,
    },
    shadow = {
      enabled = false,
    },
  },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    force_default_wallpaper = 0,
    key_press_enables_dpms = false,
    mouse_move_enables_dpms = true,
  },
  dwindle = {
    preserve_split = true,
  },
  xwayland = {
    force_zero_scaling = true,
  },
  debug = {
    disable_logs = false,
    disable_scale_checks = true,
  },
})

-- Device overrides
hl.device({
  name = "yspringtech-usb-optical-mouse",
  sensitivity = -0.5,
  accel_profile = "adaptative",
})

-- Animations
hl.animation({ leaf = "workspaces", enabled = true, speed = 0.25, bezier = "linear" })
hl.animation({ leaf = "windows", enabled = false })
hl.animation({ leaf = "fade", enabled = false })

-- Modules
require("dms.colors")
require("dms.outputs")
require("dms.binds-user")
require("dms.windowrules")
