# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/cb07e19c-52dd-483f-8ca4-34946e311c9f";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B864-7113";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home/cricro/store" = {
    device = "/dev/disk/by-uuid/ab8bbead-5ad6-40db-b940-589deb68344b";
    fsType = "ext4";
  };

  fileSystems."/home/LaEsquina/la-esquina-store" = {
    device = "/dev/disk/by-uuid/D624289724287C9D";
    fsType = "ntfs";
    options = [
      "uid=1001"
      "gid=100"
      "umask=0022"
      "nofail"
      "x-systemd.device-timeout=15s"
    ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-uuid/e69fae2f-5fb7-40f6-8e95-125308a4b0e5";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
