-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.000", position = "0x0", scale = 1, vrr = 0 })
hl.monitor({ output = "DP-1", mode = "1366x768@59.790", position = "1920x45", scale = 1, vrr = 0 })
