#cloud-config
#runcmd:
#  -   curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | NIX_CHANNEL=nixos-23.05 bash -x

# TODO uhh figure out how to make github not reject the curl due to "scraping"